### ISSUE TITLE
Mythtv server v29 supported?

### ISSUE THREAD

**Issue by mweber88** [ta264/Emby.MythTv#25]
I've installed the plugin into Emby 4.0.1.0 and configured to point to my mythtv server on the same physical host, but I get an error in the log like this:

System.TypeLoadException: System.TypeLoadException: Method 'GetProgramsAsync' in type 'Emby.MythTv.LiveTvService' from assembly 'Emby.MythTv, Version=1.0.0.8, Culture=neutral, PublicKeyToken=null' does not have an implementation.
	   at Emby.MythTv.RecordingsChannel.GetCacheKey(String userId)
	   at Emby.Server.Implementations.Channels.ChannelManager.GetChannelDataCachePath(IChannel channel, String userId, String externalFolderId, Nullable`1 sortField, Boolean sortDescending)
	   at Emby.Server.Implementations.Channels.ChannelManager.GetChannelItems(IChannel channel, User user, String externalFolderId, Nullable`1 sortField, Boolean sortDescending, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.Channels.ChannelManager.GetChannelItemsInternal(InternalItemsQuery query, IProgress`1 progress, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.Channels.ChannelManager.RefreshLatestChannelItems(IChannel channel, CancellationToken cancellationToken)

So, is this plugin operational on mythtv v29?

**Comment by mweber88** [comment]
Sorry:

mythtv v29
centOS 7.4

**Comment by ta264** [comment]
It's supported on mythtv 29 but not currently on emby 4 - the update made some breaking changes.  Fixes hopefully up in the next few days.

**Comment by ta264** [comment]
Fixes for Emby 4 are up in 1.0.9
